name: Cumio API CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: cumio-api:latest
          outputs: type=docker,dest=/tmp/cumio-api.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cumio-api
          path: /tmp/cumio-api.tar
          retention-days: 3

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cumio-api
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/cumio-api.tar

      - name: Run container
        run: docker compose up -d

      - name: Docker ps
        run: docker ps

      - name: cURL container
        run: curl http://localhost:8080/index.html | curl https://localhost:8080/index.html | exit 0

      - name: Run K6 tests
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/k6-api.js
          flags: --out json=results.json
        env:
          BASE_URL: "http://0.0.0.0:8080"

      - name: Upload K6 test results
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: results.json

  push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up GCP CLI
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cumio-api
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/cumio-api.tar

      - name: Tag and push the Docker image
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker tag cumio-api:latest europe-west3-docker.pkg.dev/$GCP_PROJECT/cumio-api/cumio-api:latest
          docker push europe-west3-docker.pkg.dev/$GCP_PROJECT/cumio-api/cumio-api:latest
