name: Cumio API CI

on:
  push:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: cumio-api:latest
          outputs: type=docker,dest=/tmp/cumio-api.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cumio-api
          path: /tmp/cumio-api.tar
          retention-days: 3

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up GCP CLI
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cumio-api
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/cumio-api.tar

      - name: Tag and push the Docker image
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker tag cumio-api:latest europe-west3-docker.pkg.dev/$GCP_PROJECT/cumio-api/cumio-api:latest
          docker push europe-west3-docker.pkg.dev/$GCP_PROJECT/cumio-api/cumio-api:latest

  test:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cumio-api
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/cumio-api.tar

      - name: Run container
        run: docker run -p 8080:8080 cumio-api:latest

      - name: Run K6 tests
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/k6-api.js
        env:
          BASE_URL: "http://localhost:8080"
