name: Cumio API CI

on:
  push:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up GCP CLI
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build and push the Docker image
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker build -t europe-west3-docker.pkg.dev/$GCP_PROJECT/cumio-api/cumio-api:latest .
          docker push europe-west3-docker.pkg.dev/$GCP_PROJECT/cumio-api/cumio-api:latest

  test:
    needs: push
    runs-on: ubuntu-latest

    services:
      cumio-api:
        image: ghcr.io/grafana/quickpizza-local:0.4.0
        ports:
          - 8080:8080
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Run K6 tests
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test/k6-api.js
        env:
          BASE_URL: "http://cumio-api:8080"
